### ISSUE TITLE
[HELP] - no connected to Jira

### ISSUE THREAD

**Issue by sebastienL** [RedMadRobot/fastlane-plugin-jira_release_notes#9]
Hello,

connection fails, the message I get is: JIRA :: HTTPError 404, Not Found

`[18:46:43]: Fetch issues from JIRA project 'ALKJ', version 'iOS 7.0(7)'
+------------------+-------------+
|          Lane Context          |
+------------------+-------------+
[18:46:44]: JIRA::HTTPError 404, Not Found`

        text = jira_release_notes(
            username: "****",
            password: "***", # password or api token
            url:      "https://***.u**e.***.fr/jira",
            project:  "ALKJ",
            version:  "iOS 7.0(7)",
            status:  "Testable",
            format: "plain"
            )

do i need to activate an option in jira server?
`url:      "https://***.u**e.***.fr/jira",` is OK via curl or website

Thanks

Sebastien

**Comment by Alexander-Ignition** [comment]
Hello, @sebastienL 

The error may have occurred due to a typo in `project`, `version`, or `status`.
These fields are case-sensitive.
If you make a typo in these fields, an error will occur that nothing was found.

Specifically, you need to create only an api token.  
But if it is not correct, another error occurred.
[How to generate an API Access Token](https://confluence.atlassian.com/cloud/api-tokens-938839638.html)

**Comment by sebastienL** [comment]
Hey, @Alexander-Ignition 

Thanks,
The fields are correct but I use a private installation Jira
I can't use https://id.atlassian.com/manage/api-tokens to generate a token

I will contact the administrator
